/**
 * Feature extraction module exports
 *
 * This module provides RFC-compliant email classification and feature extraction
 * for intelligent email prioritization.
 */

export { NewsletterGate, type EmailHeaders, type NewsletterDetectionResult } from './NewsletterGate.js';
export { AutoGeneratedGate, type AutoGeneratedDetectionResult } from './AutoGeneratedGate.js';
export { CalendarGate, type CalendarEventInfo, type CalendarDetectionResult } from './CalendarGate.js';
export { OTPGate, type OTPInfo, type OTPDetectionResult } from './OTPGate.js';
export { RelationshipScorer, type EmailHistoryStats, type RelationshipScore } from './RelationshipScorer.js';
export { ContentAnalyzer, type ContentAnalysis } from './ContentAnalyzer.js';
export {
  FeatureExtractor,
  type MessageFeatures,
  type SenderRelationship
} from './FeatureExtractor.js';
export { PriorityScorer, type PriorityScore } from './PriorityScorer.js';

/**
 * Quick reference for RFC standards implemented:
 *
 * RFC 2369 - The Use of URLs as Meta-Syntax for Core Mail List Commands (List-Unsubscribe, etc.)
 * RFC 2919 - List-Id: A Structured Field and Namespace for the Identification of Mailing Lists
 * RFC 3834 - Recommendations for Automatic Responses to Electronic Mail (Auto-Submitted header)
 * RFC 5545 - Internet Calendaring and Scheduling Core Object Specification (iCalendar)
 * RFC 6238 - TOTP: Time-Based One-Time Password Algorithm
 * RFC 8058 - Signaling One-Click Functionality for List Email Headers
 */