/**
 * RFCGates - Pure RFC-Compliant Email Classification
 *
 * Zero heuristics. Zero false positives. Pure header detection.
 *
 * This replaces the over-engineered gate files with ~60 lines of deterministic,
 * RFC-compliant detection. If an email is marked as newsletter/auto-generated,
 * it IS - guaranteed by email standards.
 *
 * Standards implemented:
 * - RFC 2369: List-Unsubscribe header (mailing list commands)
 * - RFC 2919: List-ID header (mailing list identification)
 * - RFC 3834: Auto-Submitted header (automated responses)
 * - RFC 5545: text/calendar MIME type (iCalendar)
 */

export interface EmailHeaders {
  [key: string]: string | undefined;
}

export interface Attachment {
  filename?: string;
  contentType?: string;
}

export class RFCGates {
  /**
   * RFC 2369/2919: Newsletter/Mailing List Detection
   *
   * If List-Unsubscribe or List-ID header exists, this is a mailing list.
   * Every legitimate newsletter service (Mailchimp, Substack, etc.) includes these.
   *
   * @returns true if email is from a mailing list
   */
  static isNewsletter(headers?: EmailHeaders): boolean {
    if (!headers) return false;

    // RFC 2369: List-Unsubscribe is mandatory for mailing lists
    if (headers['list-unsubscribe']) return true;

    // RFC 2919: List-ID identifies the mailing list
    if (headers['list-id']) return true;

    return false;
  }

  /**
   * RFC 3834: Auto-Generated Email Detection
   *
   * If Auto-Submitted header exists and != "no", this is auto-generated.
   * Covers: bounces, out-of-office, system notifications, auto-replies.
   *
   * Values per RFC 3834:
   * - "auto-generated": Automatically generated message
   * - "auto-replied": Automatic reply to a message
   * - "auto-notified": Delivery status notification
   *
   * @returns true if email is auto-generated
   */
  static isAutoGenerated(headers?: EmailHeaders): boolean {
    if (!headers) return false;

    const autoSubmitted = headers['auto-submitted']?.toLowerCase();

    // RFC 3834: "no" means human-generated, anything else is automated
    // If header exists and is NOT "no", it's auto-generated
    if (autoSubmitted !== undefined && autoSubmitted !== 'no') {
      return true;
    }

    return false;
  }

  /**
   * RFC 5545: Calendar Invite Detection
   *
   * If Content-Type is text/calendar or has .ics attachment, this is a calendar invite.
   * All calendar apps (Google, Outlook, Apple) use this standard.
   *
   * @returns true if email contains calendar data
   */
  static isCalendar(
    contentType?: string,
    attachments?: Attachment[]
  ): boolean {
    // Check Content-Type header for text/calendar MIME type
    if (contentType?.toLowerCase().includes('text/calendar')) {
      return true;
    }

    // Check for .ics attachments (iCalendar file format)
    if (attachments?.some(att =>
      att.filename?.toLowerCase().endsWith('.ics') ||
      att.contentType?.toLowerCase().includes('text/calendar')
    )) {
      return true;
    }

    return false;
  }

  /**
   * Extract key header values for debugging/logging
   */
  static extractHeaderInfo(headers?: EmailHeaders): {
    hasListUnsubscribe: boolean;
    hasListId: boolean;
    hasAutoSubmitted: boolean;
    autoSubmittedValue: string | null;
  } {
    return {
      hasListUnsubscribe: !!headers?.['list-unsubscribe'],
      hasListId: !!headers?.['list-id'],
      hasAutoSubmitted: !!headers?.['auto-submitted'],
      autoSubmittedValue: headers?.['auto-submitted'] || null
    };
  }

  /**
   * HEURISTIC FALLBACK: Newsletter Detection for non-RFC-compliant senders
   *
   * Some senders (Lonely Planet, The Register, etc.) don't use RFC 2369/2919 headers.
   * This provides fallback detection based on common patterns.
   *
   * Lower confidence than RFC detection - only use when RFC check fails.
   *
   * Patterns checked:
   * 1. Sender domain: mail.*, news.*, mailer.*, newsletter.*, email.*
   * 2. Sender address: info@, no-reply@, noreply@, update-*, newsletter@
   * 3. Body content: unsubscribe links in footer
   *
   * @returns true if email appears to be a newsletter (heuristic)
   */
  static isNewsletterHeuristic(
    senderEmail?: string,
    bodyText?: string,
    bodyHtml?: string
  ): boolean {
    if (!senderEmail) return false;

    const email = senderEmail.toLowerCase();
    const localPart = email.split('@')[0];
    const domain = email.split('@')[1] || '';

    // Pattern 1: Newsletter sender domains
    const newsletterDomainPatterns = [
      /^mail\./,           // mail.lonelyplanet.com
      /^news\./,           // news.theregister.co.uk
      /^mailer\./,         // mailer.company.com
      /^newsletter\./,     // newsletter.company.com
      /^email\./,          // email.company.com
      /^e\./,              // e.company.com (common pattern)
      /^updates?\./,       // update.company.com, updates.company.com
      /^notifications?\./  // notification.company.com
    ];

    for (const pattern of newsletterDomainPatterns) {
      if (pattern.test(domain)) return true;
    }

    // Pattern 2: Newsletter/marketing sender addresses
    const newsletterLocalPatterns = [
      /^info$/,              // info@
      /^no-?reply$/,         // no-reply@, noreply@
      /^newsletter/,         // newsletter@
      /^update-/,            // update-1234@
      /^notifications?$/,    // notification@, notifications@
      /^team$/,              // team@
      /^hello$/,             // hello@
      /^digest$/,            // digest@
      /^customerservice$/,   // customerservice@
      /^customer-?service$/, // customer-service@
      /^friends$/,           // friends@
      /^get$/,               // get@
      /^interests$/,         // interests@
      /^offers$/,            // offers@
      /^promo/,              // promo@, promotions@
      /^deals$/,             // deals@
      /^sales$/,             // sales@
      /^marketing$/,         // marketing@
      /^service$/            // service@
    ];

    for (const pattern of newsletterLocalPatterns) {
      if (pattern.test(localPart)) return true;
    }

    // Pattern 3: Unsubscribe link in body (strong signal)
    const body = (bodyText || '') + (bodyHtml || '');
    if (body.length > 0) {
      const unsubscribePatterns = [
        /unsubscribe/i,
        /email\s+preferences/i,
        /manage\s+subscriptions?/i,
        /opt[- ]?out/i,
        /stop\s+receiving/i
      ];

      // Must have unsubscribe AND one of the above sender patterns to trigger
      // (to avoid false positives on transactional emails with unsubscribe links)
      const hasUnsubscribe = unsubscribePatterns.some(p => p.test(body));
      if (hasUnsubscribe) {
        // Additional confirmation: sender has marketing-like characteristics
        const softSignals = [
          // Common newsletter local parts
          /^(info|hello|team|updates?|news|customerservice|friends|get|offers|promo|deals|marketing)$/,
          // Newsletter domain patterns
          /@(mail|news|email|e|updates?)\./,
          // Generic company subdomains
          /@[^@]+\.(com|io|co)\s*$/  // If sender domain looks commercial + has unsubscribe
        ];

        // If any soft signal matches OR if there are multiple unsubscribe patterns
        const multipleUnsubPatterns = unsubscribePatterns.filter(p => p.test(body)).length >= 2;
        if (softSignals.some(p => p.test(email)) || multipleUnsubPatterns) {
          return true;
        }
      }
    }

    return false;
  }

  /**
   * Combined newsletter detection: RFC first, then heuristic fallback
   *
   * @returns { isNewsletter: boolean, method: 'rfc' | 'heuristic' | 'none' }
   */
  static detectNewsletter(
    headers?: EmailHeaders,
    senderEmail?: string,
    bodyText?: string,
    bodyHtml?: string
  ): { isNewsletter: boolean; method: 'rfc' | 'heuristic' | 'none' } {
    // RFC detection has priority (100% accurate)
    if (RFCGates.isNewsletter(headers)) {
      return { isNewsletter: true, method: 'rfc' };
    }

    // Fallback to heuristics for non-compliant senders
    if (RFCGates.isNewsletterHeuristic(senderEmail, bodyText, bodyHtml)) {
      return { isNewsletter: true, method: 'heuristic' };
    }

    return { isNewsletter: false, method: 'none' };
  }

  /**
   * Transactional Email Detection
   *
   * Detects transactional emails (shipping, receipts, security alerts) based on
   * sender patterns and subject lines. These are automated but important emails
   * that should be scored differently than newsletters.
   *
   * Types:
   * - shipping: Order confirmations, tracking updates, delivery notifications
   * - receipt: Payment confirmations, invoices, billing statements
   * - security: Login alerts, verification codes, account notifications
   * - verification: Email/account verification requests
   *
   * @returns { isTransactional: boolean, type: TransactionalType }
   */
  static detectTransactional(
    senderEmail?: string,
    subject?: string
  ): { isTransactional: boolean; type: TransactionalType } {
    if (!senderEmail) return { isTransactional: false, type: null };

    const email = senderEmail.toLowerCase();
    const subj = (subject || '').toLowerCase();
    const localPart = email.split('@')[0];
    const domain = email.split('@')[1] || '';

    // SHIPPING/ORDER patterns
    const shippingPatterns = {
      sender: [
        /^orders?[@-]/,             // orders@, order@, orders-*
        /^shipping[@-]/,            // shipping@
        /^fulfillment[@-]/,         // fulfillment@
        /^delivery[@-]/,            // delivery@
        /noreply.*order/,           // noreply+order@
        /^track(ing)?[@-]/,         // track@, tracking@
        /^ship[@-]/,                // ship@
        /^package[@-]/              // package@
      ],
      subject: [
        /order (confirmed|shipped|placed|delivered|ready)/i,
        /your (order|shipment|delivery|package)/i,
        /tracking (number|info|update|information)/i,
        /has shipped|out for delivery|is on its way/i,
        /order #?\d+/i,             // Order #12345
        /shipment (update|confirmation)/i
      ]
    };

    // RECEIPT patterns
    const receiptPatterns = {
      sender: [
        /^receipts?[@+-]/,          // receipt@, receipts@
        /^billing[@-]/,             // billing@
        /^invoic(e|es|ing)[@-]/,    // invoice@, invoices@
        /^payments?[@-]/,           // payment@, payments@
        /^transactions?[@-]/        // transaction@
      ],
      subject: [
        /receipt (for|from)/i,
        /invoice #?\d+/i,
        /billing (statement|summary|notification)/i,
        /payment (received|confirmed|successful|processed)/i,
        /your (purchase|receipt|invoice|transaction)/i,
        /order (receipt|invoice|total)/i,
        /thank you for your (purchase|payment|order)/i
      ]
    };

    // SECURITY/VERIFICATION patterns
    const securityPatterns = {
      sender: [
        /^security[@-]/,            // security@
        /^no-?reply[@-].*\.(google|apple|microsoft|amazon|meta|facebook)/,  // noreply@ from major services
        /^account[@-]/,             // account@
        /^alerts?[@-]/,             // alert@, alerts@
        /^verify[@-]/,              // verify@
        /^auth(entication)?[@-]/    // auth@, authentication@
      ],
      subject: [
        /security (alert|notice|notification|update)/i,
        /sign[- ]?in (attempt|detected|from|notification)/i,
        /login (attempt|detected|from|notification|alert)/i,
        /new (device|sign[- ]?in|login|browser)/i,
        /verification code/i,
        /verify your (email|account|identity)/i,
        /confirm your (account|email|identity)/i,
        /password (reset|changed|update)/i,
        /account (locked|suspended|compromised|update)/i,
        /suspicious (activity|sign[- ]?in|login)/i,
        /two[- ]?(factor|step) (authentication|verification)/i,
        /2fa|mfa/i
      ]
    };

    // Check SHIPPING patterns
    for (const p of shippingPatterns.sender) {
      if (p.test(email)) return { isTransactional: true, type: 'shipping' };
    }
    for (const p of shippingPatterns.subject) {
      if (p.test(subj)) return { isTransactional: true, type: 'shipping' };
    }

    // Check RECEIPT patterns
    for (const p of receiptPatterns.sender) {
      if (p.test(email)) return { isTransactional: true, type: 'receipt' };
    }
    for (const p of receiptPatterns.subject) {
      if (p.test(subj)) return { isTransactional: true, type: 'receipt' };
    }

    // Check SECURITY patterns
    for (const p of securityPatterns.sender) {
      if (p.test(email)) return { isTransactional: true, type: 'security' };
    }
    for (const p of securityPatterns.subject) {
      if (p.test(subj)) return { isTransactional: true, type: 'security' };
    }

    return { isTransactional: false, type: null };
  }
}

// Type export for transactional email classification
export type TransactionalType = 'shipping' | 'receipt' | 'security' | 'verification' | null;
